export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const CHANGE_PASS = "CHANGE_PASS";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAILURE = "CHANGE_PASS_FAILURE";

export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_NAME_SUCCESS = "CHANGE_NAME_SUCCESS";
export const CHANGE_NAME_FAILURE = "CHANGE_NAME_FAILURE";

export const SET_AVATAR = "SET_AVATAR";
export const SET_AVATAR_SUCCESS = "SET_AVATAR_SUCCESS";
export const SET_AVATAR_FAILURE = "SET_AVATAR_FAILURE";

export const LOGOUT = "LOGOUT"