export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY"
export const GET_LIST_CATEGORY_SUCCESS = "GET_LIST_CATEGORY_SUCCESS"
export const GET_LIST_CATEGORY_FAILURE = "GET_LIST_CATEGORY_FAILURE"

export const GET_LIST_MOVIE_BY_CATEGORY = "GET_LIST_MOVIE_BY_CATEGORY"
export const GET_LIST_MOVIE_BY_CATEGORY_SUCCESS = "GET_LIST_MOVIE_BY_CATEGORY_SUCCESS"
export const GET_LIST_MOVIE_BY_CATEGORY_FAILURE = "GET_LIST_MOVIE_BY_CATEGORY_FAILURE"

export const GET_INFO_MOVIE = "GET_INFO_MOVIE"
export const GET_INFO_MOVIE_SUCCESS = "GET_INFO_MOVIE_SUCCESS"
export const GET_INFO_MOVIE_FAILURE = "GET_INFO_MOVIE_FAILURE"

export const SEARCH_MOVIE_LIKE_NAME = "SEARCH_MOVIE_LIKE_NAME"
export const SEARCH_MOVIE_LIKE_NAME_SUCCESS = "SEARCH_MOVIE_LIKE_NAME_SUCCESS"
export const SEARCH_MOVIE_LIKE_NAME_FAILURE = "SEARCH_MOVIE_LIKE_NAME_FAILURE"

export const GET_NEWEST_MOVIE = "GET_NEWEST_MOVIE"
export const GET_NEWEST_MOVIE_SUCCESS = "GET_NEWEST_MOVIE_SUCCESS"
export const GET_NEWEST_MOVIE_FAILURE = "GET_NEWEST_MOVIE_FAILURE"

export const GET_LIST_NEWEST_MOVIE = "GET_LIST_NEWEST_MOVIE"
export const GET_LIST_NEWEST_MOVIE_SUCCESS = "GET_LIST_NEWEST_MOVIE_SUCCESS"
export const GET_LIST_NEWEST_MOVIE_FAILURE = "GET_LIST_NEWEST_MOVIE_FAILURE"

export const GET_LIST_MOVIE = "GET_LIST_MOVIE"
export const GET_LIST_MOVIE_SUCCESS = "GET_LIST_MOVIE_SUCCESS"
export const GET_LIST_MOVIE_FAILURE = "GET_LIST_MOVIE_FAILURE"